### ISSUE TITLE
Stopped passing selected text and prompts to ChatGPT.

### ISSUE THREAD

**Issue by Boilerplate4u** [lunu-bounir/ask-from-chatgpt#1]
Hi! The "Ask from ChatGPT" add-on for Google Chrome has stopped working. It no longer passes selected text and prompt to ChatGPT.

**Comment by lunu-bounir** [comment]
Thanks for the report. Should be fixed by 0.1.5 release

**Comment by Boilerplate4u** [comment]
I can confirm the new 0.1.5 release made it work again. Greatly appreciate the add-on service! Thanks! 👍
